services:
  - type: web
    name: news-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -X utf8 server.py
    envVars:
      - key: PORT
        value: 8585
